export interface MockAddress {
  fullAddress: string;
  province: string;
  city: string;
  district: string;
  postalCode: string;
  lat: number;
  lng: number;
  tags: string[];
}

export const mockAddresses: MockAddress[] = [
  {
    fullAddress: 'Jl. Sudirman No. 28, RT.5/RW.3, Senayan, Kebayoran Baru',
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    district: 'Kebayoran Baru',
    postalCode: '12190',
    lat: -6.2297,
    lng: 106.8028,
    tags: ['jakarta', 'sudirman', 'senayan', 'kebayoran'],
  },
  {
    fullAddress: 'Jl. Thamrin No. 12, Menteng, Jakarta Pusat',
    province: 'DKI Jakarta',
    city: 'Jakarta Pusat',
    district: 'Menteng',
    postalCode: '10310',
    lat: -6.1888,
    lng: 106.8227,
    tags: ['jakarta', 'thamrin', 'menteng'],
  },
  {
    fullAddress: 'Perumahan BSD Blok A/5, Lengkong Gudang, Serpong',
    province: 'Banten',
    city: 'Tangerang Selatan',
    district: 'Serpong',
    postalCode: '15321',
    lat: -6.3388,
    lng: 106.6926,
    tags: ['tangerang', 'bsd', 'serpong'],
  },
  {
    fullAddress: 'Jl. Raya Padjajaran No. 99, Hegarmanah, Jatinangor',
    province: 'Jawa Barat',
    city: 'Sumedang',
    district: 'Jatinangor',
    postalCode: '45363',
    lat: -6.9222,
    lng: 107.7589,
    tags: ['bandung', 'jatinangor', 'padjajaran'],
  },
  {
    fullAddress: 'Jl. Riau No. 23, Citarum, Bandung Wetan',
    province: 'Jawa Barat',
    city: 'Bandung',
    district: 'Bandung Wetan',
    postalCode: '40115',
    lat: -6.9039,
    lng: 107.6106,
    tags: ['bandung', 'riau', 'citarum'],
  },
  {
    fullAddress: 'Jl. Malioboro No. 15, Suryatmajan, Danurejan',
    province: 'DI Yogyakarta',
    city: 'Yogyakarta',
    district: 'Danurejan',
    postalCode: '55213',
    lat: -7.7936,
    lng: 110.3666,
    tags: ['yogyakarta', 'malioboro', 'suryatmajan'],
  },
  {
    fullAddress: 'Jl. Tunjungan No. 88, Genteng, Surabaya Pusat',
    province: 'Jawa Timur',
    city: 'Surabaya',
    district: 'Genteng',
    postalCode: '60275',
    lat: -7.2594,
    lng: 112.7378,
    tags: ['surabaya', 'tunjungan', 'genteng'],
  },
  {
    fullAddress: 'Jl. Basuki Rahmat No. 50, Embong Kaliasin, Genteng',
    province: 'Jawa Timur',
    city: 'Surabaya',
    district: 'Genteng',
    postalCode: '60271',
    lat: -7.2642,
    lng: 112.7387,
    tags: ['surabaya', 'basuki rahmat', 'embong'],
  },
  {
    fullAddress: 'Kompleks Podomoro Golf View Blok C/12, Medan Sunggal',
    province: 'Sumatera Utara',
    city: 'Medan',
    district: 'Medan Sunggal',
    postalCode: '20128',
    lat: 3.5775,
    lng: 98.6533,
    tags: ['medan', 'podomoro', 'sunggal'],
  },
  {
    fullAddress: 'Jl. Diponegoro No. 45, Merdeka, Medan Baru',
    province: 'Sumatera Utara',
    city: 'Medan',
    district: 'Medan Baru',
    postalCode: '20154',
    lat: 3.5728,
    lng: 98.6685,
    tags: ['medan', 'diponegoro', 'merdeka'],
  },
  {
    fullAddress: 'Jl. Bypass Ngurah Rai No. 200, Kuta, Badung',
    province: 'Bali',
    city: 'Badung',
    district: 'Kuta',
    postalCode: '80361',
    lat: -8.7235,
    lng: 115.1730,
    tags: ['bali', 'kuta', 'ngurah rai'],
  },
  {
    fullAddress: 'Jl. Sunset Road No. 88, Seminyak, Kuta',
    province: 'Bali',
    city: 'Badung',
    district: 'Kuta',
    postalCode: '80361',
    lat: -8.6916,
    lng: 115.1586,
    tags: ['bali', 'seminyak', 'sunset road'],
  },
  {
    fullAddress: 'Jl. Sultan Hasanuddin No. 62, Melayu, Makassar',
    province: 'Sulawesi Selatan',
    city: 'Makassar',
    district: 'Makassar',
    postalCode: '90121',
    lat: -5.1475,
    lng: 119.4288,
    tags: ['makassar', 'hasanuddin', 'melayu'],
  },
  {
    fullAddress: 'Jl. Adinegoro No. 10, Lubuk Buaya, Koto Tangah',
    province: 'Sumatera Barat',
    city: 'Padang',
    district: 'Koto Tangah',
    postalCode: '25586',
    lat: -0.8683,
    lng: 100.3619,
    tags: ['padang', 'adinegoro', 'koto tangah'],
  },
  {
    fullAddress: 'Perumahan Graha Kencana Blok E/9, Palembang',
    province: 'Sumatera Selatan',
    city: 'Palembang',
    district: 'Sukarami',
    postalCode: '30961',
    lat: -2.9624,
    lng: 104.7494,
    tags: ['palembang', 'graha kencana', 'sukarami'],
  },
  {
    fullAddress: 'Jl. A. Yani No. 80, Kebonrejo, Kalianda',
    province: 'Lampung',
    city: 'Lampung Selatan',
    district: 'Kalianda',
    postalCode: '35551',
    lat: -5.6315,
    lng: 105.5906,
    tags: ['lampung', 'kalianda', 'ayani'],
  },
  {
    fullAddress: 'Jl. Soekarno Hatta No. 257, Sario, Manado',
    province: 'Sulawesi Utara',
    city: 'Manado',
    district: 'Sario',
    postalCode: '95114',
    lat: 1.4926,
    lng: 124.8479,
    tags: ['manado', 'sario', 'soekarno hatta'],
  },
  {
    fullAddress: 'Jl. Ahmad Yani No. 1, Banjar, Banjarmasin Selatan',
    province: 'Kalimantan Selatan',
    city: 'Banjarmasin',
    district: 'Banjarmasin Selatan',
    postalCode: '70231',
    lat: -3.3248,
    lng: 114.5921,
    tags: ['banjarmasin', 'ahmad yani'],
  },
  {
    fullAddress: 'Jl. Pahlawan No. 30, Bugis, Pontianak Selatan',
    province: 'Kalimantan Barat',
    city: 'Pontianak',
    district: 'Pontianak Selatan',
    postalCode: '78117',
    lat: -0.0236,
    lng: 109.3415,
    tags: ['pontianak', 'pahlawan', 'bugis'],
  },
  {
    fullAddress: 'Jl. Siliwangi No. 44, Cimone, Karawaci',
    province: 'Banten',
    city: 'Tangerang',
    district: 'Karawaci',
    postalCode: '15115',
    lat: -6.1865,
    lng: 106.6092,
    tags: ['tangerang', 'karawaci', 'siliwangi'],
  },
  {
    fullAddress: 'Jl. Margonda Raya No. 100, Pondok Cina, Beji',
    province: 'Jawa Barat',
    city: 'Depok',
    district: 'Beji',
    postalCode: '16424',
    lat: -6.3708,
    lng: 106.8299,
    tags: ['depok', 'margonda', 'pondok cina'],
  },
  {
    fullAddress: 'Perumahan Citra Garden City Blok B/7, Kalideres',
    province: 'DKI Jakarta',
    city: 'Jakarta Barat',
    district: 'Kalideres',
    postalCode: '11840',
    lat: -6.1461,
    lng: 106.7188,
    tags: ['jakarta', 'kalideres', 'citra garden'],
  },
  {
    fullAddress: 'Jl. Kramat Raya No. 50, Kramat, Senen',
    province: 'DKI Jakarta',
    city: 'Jakarta Pusat',
    district: 'Senen',
    postalCode: '10450',
    lat: -6.1900,
    lng: 106.8475,
    tags: ['jakarta', 'senen', 'kramat'],
  },
  {
    fullAddress: 'Jl. Gatot Subroto Kav. 56, Kuningan Timur, Setiabudi',
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    district: 'Setiabudi',
    postalCode: '12950',
    lat: -6.2256,
    lng: 106.8268,
    tags: ['jakarta', 'gatot subroto', 'kuningan'],
  },
  {
    fullAddress: 'Jl. Teuku Umar No. 30, Dauh Puri Klod, Denpasar Barat',
    province: 'Bali',
    city: 'Denpasar',
    district: 'Denpasar Barat',
    postalCode: '80113',
    lat: -8.6537,
    lng: 115.2079,
    tags: ['denpasar', 'teuku umar', 'dauh puri'],
  },
  {
    fullAddress: 'Jl. Cikutra No. 156, Cikutra, Cibeunying Kidul',
    province: 'Jawa Barat',
    city: 'Bandung',
    district: 'Cibeunying Kidul',
    postalCode: '40124',
    lat: -6.8810,
    lng: 107.6394,
    tags: ['bandung', 'cikutra', 'cibeunying'],
  },
  {
    fullAddress: 'Jl. MT Haryono No. 88, Dinoyo, Lowokwaru',
    province: 'Jawa Timur',
    city: 'Malang',
    district: 'Lowokwaru',
    postalCode: '65144',
    lat: -7.9516,
    lng: 112.6245,
    tags: ['malang', 'mt haryono', 'lowokwaru'],
  },
  {
    fullAddress: 'Jl. Pesantren No. 12, Cimahi, Cimahi Selatan',
    province: 'Jawa Barat',
    city: 'Cimahi',
    district: 'Cimahi Selatan',
    postalCode: '40522',
    lat: -6.8893,
    lng: 107.5451,
    tags: ['cimahi', 'pesantren', 'cimahi selatan'],
  },
  {
    fullAddress: 'Perumahan Griya Indah Permai Blok D/3, Bekasi Timur',
    province: 'Jawa Barat',
    city: 'Bekasi',
    district: 'Bekasi Timur',
    postalCode: '17111',
    lat: -6.2470,
    lng: 107.0184,
    tags: ['bekasi', 'griya indah'],
  },
  {
    fullAddress: 'Jl. Veteran No. 17, Purwodinatan, Semarang Tengah',
    province: 'Jawa Tengah',
    city: 'Semarang',
    district: 'Semarang Tengah',
    postalCode: '50131',
    lat: -6.9900,
    lng: 110.4234,
    tags: ['semarang', 'veteran', 'purwodinatan'],
  },
];

export function searchMockAddresses(query: string): MockAddress[] {
  if (!query || query.length < 2) return [];
  const lower = query.toLowerCase();
  return mockAddresses
    .filter((addr) =>
      addr.tags.some((t) => t.includes(lower)) ||
      addr.fullAddress.toLowerCase().includes(lower) ||
      addr.city.toLowerCase().includes(lower) ||
      addr.district.toLowerCase().includes(lower) ||
      addr.province.toLowerCase().includes(lower)
    )
    .slice(0, 6);
}
